Fix installation problem
When running the "Build"->"Check" option in RStudio I received
the following error:
```
Error: package or namespace load failed for ‘ddh’ in namespaceExport(ns, exports):
 undefined exports: load_ddh_data, load_ddh_db, load_ddh_feather
```
These functions have been removed from R/helper.R:
https://github.com/matthewhirschey/ddh/commit/991bae60ac06d33827d47ffa088ba1583f425064